### ISSUE TITLE
setTrackClicksAllowed() flag doesn't behave as expected

### ISSUE THREAD

**Issue by themichaelscott** [brianwernick/RecyclerExt#23]
First... I love the library!  Thanks!
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- RecyclerExt version: `2.0.0`
- Device OS version: `7.0`
- Device Manufacturer: `Huawei`
- Device Name: `Nexus 6P`
###### Reproduction Steps
1. `setTrackClicksAllowed(true)`
2. open activity with a RecyclerView
3. Click in the track
###### Expected Result

The javadoc for `setTrackClicksAllowed(boolean allowed)` reads:
`Specifies if clicks on the track should scroll to that position.`
I expect the handle to jump to that position in the track and set the RecyclerView to that position as well. 
###### Actual Result

The handle doesn't move and the RecyclerView doesn't scroll to that position.  Instead, the handle is controlled from wherever the ACTION_DOWN took place.

**Comment by brianwernick** [comment]
This is an unintended consequence of https://github.com/brianwernick/RecyclerExt/commit/8ad5648889947dfd622c3104c2d319e52b14297b
