### ISSUE TITLE
Allow for FastScroll handle to be triggered and grabbed even when it's hidden

### ISSUE THREAD

**Issue by themichaelscott** [brianwernick/RecyclerExt#24]
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
###### Include the following:
- RecyclerExt version: `2.0.0`
- Device OS version: `6.0`
- Devide Manufacturer: `Huawei`
- Device Name: `Nexus 6P`
###### Reproduction Steps
1. Leave `setHideHandleAllowed = true`
2. On device, open Activity with FastScroll enabled
3. Attempt to begin scroll in right margin (when the FastScroll is not visible)
###### Expected Result

FastScroll / Handle appears immediately and scrolls the RecyclerView to that position.  Handle can be controlled after that.
###### Actual Result

Nothing. The FastScroll handle is not visible until a scroll has been initiated on the RecyclerView.  At that point, the handle can be grabbed and moved.

**Comment by brianwernick** [comment]
How is this different from `setTrackClicksAllowed()` functionality? (i.e. #23)

**Comment by themichaelscott** [comment]
Does setTrackClicksAllowed allow the track to be clicked even if the track/handle has autohidden?  If it does, then this is the same issue.  If not, then I'd like it to be able to.

**Comment by brianwernick** [comment]
It does. Unlike the Now Launcher (and others) quick scroll, the track isn't actually a visible field, meaning that it is always technically there.

**Comment by themichaelscott** [comment]
Awesome!  I'll close this issue.

**Comment by brianwernick** [comment]
It looks like I'm wrong. At some point this functionality existed as a side effect of how dragging was handled, in more recent updates it no longer exists.

**Comment by brianwernick** [comment]
Fixed/Updated in https://github.com/brianwernick/RecyclerExt/commit/c1a53e12b6c00ad70201676e3b443edb2a567e28
